language: c
sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - liblocal-lib-perl
    - libxml2-dev
    - libsqlite3-dev
    - libsasl2-dev
    - libssl-dev
    - libopendkim-dev
    - libcunit1-dev
    - libpcre3-dev
    - uuid-dev
    - libdb-dev
    - libbsd-dev
    - libmilter-dev
    - graphviz
    - doxygen
    - help2man
    - python-docutils
    - python-pygments
    - libmagic-dev
    - pkg-config
env:
  global:
  - CYRUS_USER=travis
  - CYRUSLIBS="/usr/local/cyruslibs"
  - PKG_CONFIG_PATH="$CYRUSLIBS/lib/pkgconfig:$PKG_CONFIG_PATH"
  - LDFLAGS="-Wl,-rpath,$CYRUSLIBS/lib -Wl,-rpath,$CYRUSLIBS/lib/x86_64-linux-gnu"
  - XAPIAN_CONFIG="$CYRUSLIBS/bin/xapian-config-1.5"
  - CPPFLAGS="-I/usr/local/cyruslibs/include"
  - PATH="$CYRUSLIBS/bin:$PATH"
  - USE_CCACHE=1
cache:
  apt: true
  ccache: true
os: linux
compiler: gcc
install:
# cassandane
- sudo sh -c 'echo 1 > /proc/sys/kernel/core_uses_pid'
- sudo sh -c 'echo 1 > /proc/sys/fs/suid_dumpable'
- ulimit -c unlimited
- sudo mkdir /var/tmp/cass
- sudo chmod 777 /var/tmp/cass
- curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
- sudo cpanm --notest experimental
- sudo cpanm --notest AnyEvent
- sudo cpanm --notest BSD::Resource
- sudo cpanm --notest Clone
- sudo cpanm --notest Config::IniFiles
- sudo cpanm --notest Convert::Base64
- sudo cpanm --notest Data::ICal
- sudo cpanm --notest Data::ICal::TimeZone
- sudo cpanm --notest Data::UUID
- sudo cpanm --notest DateTime
- sudo cpanm --notest DateTime::Format::ICal
- sudo cpanm --notest DateTime::Format::ISO8601
- sudo cpanm --notest Encode::IMAPUTF7
- sudo cpanm --notest File::LibMagic
- sudo cpanm --notest File::Slurp
- sudo cpanm --notest File::chdir
- sudo cpanm --notest HTTP::Tiny
- sudo cpanm --notest IO::Socket::INET6
- sudo cpanm --notest IO::Stringy
- sudo cpanm --notest JSON
- sudo cpanm --notest JSON::XS
- sudo cpanm --notest List::Pairwise
- sudo cpanm --notest MIME::Types
- sudo cpanm --notest Mail::IMAPTalk
- sudo cpanm --notest Math::Int64
- sudo cpanm --notest Net::LDAP::Server
- sudo cpanm --notest Net::Server
- sudo cpanm --notest News::NNTPClient
- sudo cpanm --notest String::CRC32
- sudo cpanm --notest Test::Unit
- sudo cpanm --notest Text::LevenshteinXS
- sudo cpanm --notest Text::VCardFast
- sudo cpanm --notest Tie::DataUUID
- sudo cpanm --notest Unix::Syslog
- sudo cpanm --notest XML::DOM
- sudo cpanm --notest XML::Fast
- sudo cpanm --notest XML::Generator
- sudo cpanm --notest XML::Spice
- sudo cpanm --notest https://github.com/cyrusimap/Mail-JMAPTalk.git
- sudo cpanm --notest https://github.com/cyrusimap/Net-DAVTalk.git
- sudo cpanm --notest https://github.com/cyrusimap/Net-CalDAVTalk.git
- sudo cpanm --notest https://github.com/cyrusimap/Net-CardDAVTalk.git
- git clone -b travis --single-branch https://github.com/wolfsage/cassandane.git cassandane

# libjanson
- git clone -b cyrus --single-branch https://github.com/cyrusimap/jansson.git janson
- pushd janson
- "autoreconf -v -i"
- "./configure --enable-silent-rules --prefix=$CYRUSLIBS"
- make -j 8
- sudo make install
- popd #janson

# libical
- git clone -b cyrus --single-branch https://github.com/cyrusimap/libical.git libical
- pushd libical
- mkdir build
- cd build
- cmake -DENABLE_GTK_DOC=OFF -DCMAKE_INSTALL_PREFIX=$CYRUSLIBS -DICU_BASE=$CYRUSLIBS -DUSE_BUILTIN_TZDATA=true -DCMAKE_SKIP_RPATH=ON -DICAL_ALLOW_EMPTY_PROPERTIES=true ..
- make
- sudo make install
- popd #libical

# Xapian
- git clone -b cyrus --single-branch https://github.com/cyrusimap/xapian.git xapian
- pushd xapian
- "./bootstrap"
- "./configure --enable-silent-rules --prefix=$CYRUSLIBS"
- pushd xapian-core
- make -j 8
- sudo make install
- popd #xapian-core
- popd #xapian
before_script:
- ccache --version
- ccache --zero-stats
- autoreconf -i -s
- ./configure CFLAGS="-W -Wno-unused-parameter -g -O0 -Wall -Wextra -Werror -fPIC"
  --enable-coverage --enable-calalarmd --enable-autocreate --enable-nntp --enable-http
  --enable-jmap --enable-xapian --enable-unit-tests --enable-replication --with-openssl=yes
  --enable-murder --enable-idled --enable-sieve --enable-jmap --prefix=/usr/cyrus/  --with-cyrus-prefix=/usr/cyrus 
- make
- sudo make install
- sudo make install-binsymlinks
- sudo cp tools/mkimap /usr/cyrus/bin/mkimap
script:
# - make check
- pushd cassandane
- make
- sudo perl ./testrunner.pl -v --config ../cassandane.ini -f pretty -j 8
after_script:
- sudo cat /var/log/syslog
- sudo cat /var/log/messages
branches:
  only:
  - master
  - travis
  - cyrus-imapd-3.0
notifications:
  slack:
    on_pull_requests: false
    on_success: change
    on_failure: always
    secure:
      bh4PiwcHYwn2qjKgidSKX6Ibq/Gt8+q6IL7YDWlfpDPYCuzdzSHBpm8qMpmBIjTemnsragJeR4pO9XEX20nhE9Lr7915wiBmYWqcmvcJGpJ1/nJz2lJYtBKl/dKZguQn3g4A+JgjUuXgzllI4ZsbbRkzL8dBC+py34p4ANtMKycXeGCwysnPfHav5VxQQnOsJUbIKDJiJPON2cR7e8quE6WpS1mEzUD+kaRWMUImKktMX1hrQH/71tNNMTqv0eHewci1akaZecFtXQi8D9Yfh1YBm8yxdLI9EgnglonEgbBCGG6WRODcxu/gEJlvXFMN+c4ojoyq4lNGnEqzLjDDVI1LoCNUcWbMFFhIGAA1SE+71fwDlKjLxUzodgJPb/yrWy4uwx8eBM3W8PIhFgZyo0irlV/0U3zNFWjjNPTRXUNNIZQu2XDLAhpiRZbMn4zsvydq2ngWnTdJfgpycYiBfL5zNdwdPpAQomQLl1JakWqyMSBZtz3Hbv3vRmb4rIogh5AHuwxKQrK5JNI9eZ5yPI7eUEpTq1nYD7syZPDj3gddjdteBx8ShjHH6ddteQX2OSUXwtiF90cEgYq0z8j2HxaNRIVrkeUNyeRTZXZ0wxWM7Fcz0Z7fRzsv1CXZwjDPmxARiIhbVhXxTgbED9+i2aCH9aZNrMTqoRUQWjLzgXw=
