#!perl
use Cassandane::Tiny;
use Cassandane::TestEntity::Factory::ContactCard;

sub test_card_set_multiple_addressbookids
    :needs_dependency_icalvcard
{
    my ($self) = @_;
    my $user = $self->default_user;
    my $jmap = $user->jmap;

    my $def_abook = $user->addressbooks->default;
    my $abookid1 = $def_abook->id;

    my $new_abook = $user->addressbooks->create;
    my $abookid2 = $new_abook->id;

    my $def_card_props = {};
    Cassandane::TestEntity::Factory::ContactCard->fill_in_creation_defaults($def_card_props);

    xlog $self, "attempt to create a card in multiple addressbooks";

    my $res = $jmap->request([[
        'ContactCard/set', {
            create => {
                "1" => {
                    %$def_card_props,
                    addressBookIds => {
                        $abookid1 => JSON::true,
                        $abookid2 => JSON::true
                    }
                }
            }
        },
    ]]);

    $self->assert_cmp_deeply(
        superhashof({
            notCreated => {
                1 => {
                    type => 'invalidProperties',
                    properties => [ 'addressBookIds' ],
                },
            },
        }),
        $res->sentence(0)->arguments,
    );

    xlog $self, "create a card in a single addressbook";

    $res = $jmap->request([[
        'ContactCard/set', {
            create => {
                "1" => {
                    %$def_card_props,
                    addressBookIds => {
                        $abookid1 => JSON::true
                    }
                }
            }
        }
    ]]);
    $res->assert_single_successful_set("ContactCard/set");

    my $id = $res->single_sentence->as_set->created_id('1');

    xlog $self, "attempt to update a card to be in multiple addressbooks";
    $res = $jmap->request([[
        'ContactCard/set', {
            update => {
                $id => {
                    addressBookIds => {
                        $abookid1 => JSON::true,
                        $abookid2 => JSON::true
                    }
                }
            }
         },
    ]]);

    $self->assert_cmp_deeply(
        superhashof({
            notUpdated => {
                $id => {
                    type => 'invalidProperties',
                    properties => [ 'addressBookIds' ],
                },
            },
        }),
        $res->sentence(0)->arguments,
    );

    xlog $self, "attempt to patch a card be in multiple addressbooks";
    $res = $jmap->request([[
        'ContactCard/set', {
            update => {
                $id => {
                    "addressBookIds/$abookid2" => JSON::true
                }
            }
         },
    ]]);

    $self->assert_cmp_deeply(
        superhashof({
            notUpdated => {
                $id => {
                    type => 'invalidProperties',
                    properties => [ 'addressBookIds' ],
                },
            },
        }),
        $res->sentence(0)->arguments,
    );

    xlog $self, "patch a card, moving it between addressbooks";
    $res = $jmap->request([[
        'ContactCard/set', {
            update => {
                $id => {
                    "addressBookIds/$abookid1" => undef,
                    "addressBookIds/$abookid2" => JSON::true
                }
            }
         },
    ]]);

    $res->assert_single_successful_set("ContactCard/set");
    $self->assert_not_null($res->sentence(0)->arguments->{updated}{$id});
}
