#!perl
use Cassandane::Tiny;

sub test_card_query_group_with_member
    ($self)
{
    my $user = $self->default_user;
    my $jmap = $self->{jmap};

    my $card = $user->contacts->create;
    my $group = $user->contacts->create_group;

    # Query for each in turn
    my $res = $jmap->CallMethods([[
      'ContactCard/query', { filter => { uid => $card->uid } }, "R1"
    ]]);
    $self->assert_deep_equals($res->[0][1]{ids}, [ $card->id ]);

    $res = $jmap->CallMethods([[
      'ContactCard/query', { filter => { uid => $group->uid } }, "R1"
    ]]);
    $self->assert_deep_equals($res->[0][1]{ids}, [ $group->id ]);

    # Now add the contact to the group
    $group->add_member($card);

    # query should still work!
    $res = $jmap->CallMethods([[
      'ContactCard/query', { filter => { uid => $card->uid } }, "R1"
    ]]);
    $self->assert_deep_equals($res->[0][1]{ids}, [ $card->id ]);

    $res = $jmap->CallMethods([[
      'ContactCard/query', { filter => { uid => $group->uid } }, "R1"
    ]]);
    $self->assert_deep_equals($res->[0][1]{ids}, [ $group->id ]);

}
