#!perl
use Cassandane::Tiny;

sub test_card_query_windowing
    :min_version_3_9
    ($self)
{
    my $user = $self->default_user;
    my $jmap = $self->{jmap};

    my $card1 = $user->contacts->create({
      uid => 'XXX-UID-1',
      organizations => {
        o1 => { name => 'companyB' },
      },
    });

    my $card2 = $user->contacts->create({
      uid => 'XXX-UID-2',
      organizations => {
        o1 => { name => 'companyA' },
      },
    });

    my $card3 = $user->contacts->create({
      uid => 'XXX-UID-3',
      organizations => {
        o1 => { name => 'companyB' },
      },
    });

    my $card4 = $user->contacts->create({
      uid => 'XXX-UID-4',
      organizations => {
        o1 => { name => 'companyC' },
      },
    });

    xlog $self, "run query with windowing";
    my $res = $jmap->CallMethods([
        ['ContactCard/query', {
            sort => [{
                property => 'uid',
            }],
            limit => 2,
        }, 'R1'],
        ['ContactCard/query', {
            sort => [{
                property => 'uid',
            }],
            limit => 2,
            position => 2,
        }, 'R2'],
        ['ContactCard/query', {
            sort => [{
                property => 'uid',
            }],
            anchor => $card3->id,
            anchorOffset => -1,
            limit => 2,
        }, 'R3'],
        ['ContactCard/query', {
            sort => [{
                property => 'uid',
            }],
            limit => 2,
            position => -2,
        }, 'R4'],
    ]);
    # Request 1
    $self->assert_deep_equals([
            $card1->id,
            $card2->id,
        ], $res->[0][1]{ids}
    );
    $self->assert_num_equals(0, $res->[0][1]{position});
    $self->assert_num_equals(4, $res->[0][1]{total});
    # Request 2
    $self->assert_deep_equals([
            $card3->id,
            $card4->id,
        ], $res->[1][1]{ids}
    );
    $self->assert_num_equals(2, $res->[1][1]{position});
    $self->assert_num_equals(4, $res->[1][1]{total});
    # Request 3
    $self->assert_deep_equals([
            $card2->id,
            $card3->id,
        ], $res->[2][1]{ids}
    );
    $self->assert_num_equals(1, $res->[2][1]{position});
    $self->assert_num_equals(4, $res->[2][1]{total});
    # Request 4
    $self->assert_deep_equals([
            $card3->id,
            $card4->id,
        ], $res->[3][1]{ids}
    );
    $self->assert_num_equals(2, $res->[3][1]{position});
    $self->assert_num_equals(4, $res->[3][1]{total});
}
