#!perl
use Cassandane::Tiny;

sub test_card_query_multi_sort
    :min_version_3_9
    ($self)
{
    my $user = $self->default_user;
    my $jmap = $self->{jmap};

    xlog $self, "create cards";
    my $card1 = $user->contacts->create({
      uid => 'XXX-UID-1',
      organizations => {
        o1 => { name => 'companyB' },
      },
    });

    my $card2 = $user->contacts->create({
      uid => 'XXX-UID-2',
      organizations => {
        o1 => { name => 'companyA' },
      },
    });

    my $card3 = $user->contacts->create({
      uid => 'XXX-UID-3',
      organizations => {
        o1 => { name => 'companyB' },
      },
    });

    my $card4 = $user->contacts->create({
      uid => 'XXX-UID-4',
      organizations => {
        o1 => { name => 'companyC' },
      },
    });

    xlog $self, "sort by multi-dimensional comparator";
    my $res = $jmap->CallMethods([
        ['ContactCard/query', {
            sort => [{
                property => 'organization',
            }, {
                property => 'uid',
                isAscending => JSON::false,
            }],
        }, 'R2'],
    ]);
    $self->assert_deep_equals([
            $card2->id,
            $card3->id,
            $card1->id,
            $card4->id,
        ], $res->[0][1]{ids}
    );
}
