#!perl
use Cassandane::Tiny;
use Test::Deep ':v1';

sub test_dblookup_uid2emails
    :JMAPExtensions :NoAltNameSpace
{
    my ($self) = @_;

    my $user = $self->default_user;
    my $imap = $user->imap;
    my $other = $self->{instance}->create_user("other");
    my $other2 = $self->{instance}->create_user("other2");
    my $admin = $self->{adminstore}->get_client();

    $_->jmap->DefaultUsing([
        'urn:ietf:params:jmap:core',
        'urn:ietf:params:jmap:contacts',
        'https://cyrusimap.org/ns/jmap/contacts',
        'https://cyrusimap.org/ns/jmap/debug',
    ]) for ($other, $other2);

    $admin->create("user.other.#addressbooks.Shared", ['TYPE', 'ADDRESSBOOK']);
    my $abookId = $admin->get_response_code('mailboxid')->[0];
    $admin->setacl("user.other.#addressbooks.Shared", "cassandane", "lr") or die;
    $imap->subscribe("user.other.#addressbooks.Shared");

    $admin->create("user.other2.#addressbooks.Shared", ['TYPE', 'ADDRESSBOOK']);
    my $abookId2 = $admin->get_response_code('mailboxid')->[0];
    $admin->setacl("user.other2.#addressbooks.Shared", "cassandane", "lr") or die;
    $imap->subscribe("user.other2.#addressbooks.Shared");

    $admin->create("user.other2.#addressbooks.Shared2", ['TYPE', 'ADDRESSBOOK']);
    my $abookId3 = $admin->get_response_code('mailboxid')->[0];
    $admin->setacl("user.other2.#addressbooks.Shared2", "cassandane", "lr") or die;
    $imap->subscribe("user.other2.#addressbooks.Shared2");

    $admin->create("user.other2.#addressbooks.Unshared", ['TYPE', 'ADDRESSBOOK']);
    my $abookId4 = $admin->get_response_code('mailboxid')->[0];

    # translate mailboxids to addressbookids
    substr($abookId, 0, 1) = "R";
    substr($abookId2, 0, 1) = "R";
    substr($abookId3, 0, 1) = "R";
    substr($abookId4, 0, 1) = "R";

    my $abook = $other->addressbooks->get($abookId);
    my $shared1 = $abook->create_card({
        emails => {
            e1 => {
                address => 'sharedcontact@local'
            }
        },
    });

    my $abook2 = $other2->addressbooks->get($abookId2);
    my $shared2 = $abook2->create_card({
        emails => {
            e1 => {
                address => 'sharedcontact2@local'
            }
        },
    });

    my $abook4 = $other2->addressbooks->get($abookId4);
    my $unshared1 = $abook4->create_card({
        emails => {
            e1 => {
                address => 'unsharedcontact@local'
            }
        },
    });

    my $own_abook = $user->addressbooks->create;
    my $own1 = $own_abook->create_card({
        emails => {
            e1 => {
                address => 'ownContact@local'
            }
        },
    });

    my $owngroup1 = $own_abook->create_card({
        kind => 'group',
        members => {
            $shared1->uid => JSON::true,
            $shared2->uid => JSON::true,
        },
        emails => {
            e1 => {
                address => 'ownGroup@local'
            }
        },
    });

    my $abook3 = $other2->addressbooks->get($abookId3);

    my $sharedgroup1 = $abook3->create_card({
        kind => 'group',
        members => {
            $own1->uid    => JSON::true,
            $shared1->uid => JSON::true,
        },
    });

    my $http = $self->{instance}->get_service("http");

    my $adminJmap = Mail::JMAPTalk->new(
        user => 'admin',
        password => 'pass',
        host => $http->host(),
        port => $http->port(),
        scheme => 'http',
        url => '/jmap/',
    );

    my $dbLookupUrl = "http://"
        . $http->host . ":" . $http->port
        . "/dblookup/uid2emails";

    # lookup ownContactUid
    my $res = $adminJmap->ua->get($dbLookupUrl, {
        headers => {
            User => 'cassandane',
            Key => $own1->uid,
        },
    });
    $self->assert_deep_equals([ 'ownContact@local' ],
                              decode_json($res->{content}));

    # lookup sharedContactUid
    $res = $adminJmap->ua->get($dbLookupUrl, {
        headers => {
            User => 'cassandane',
            Key => $shared1->uid,
        },
    });
    $self->assert_deep_equals([ 'sharedcontact@local' ],
                              decode_json($res->{content}));

    # other2 addressbook is NOT shared with cassandane
    $res = $adminJmap->ua->get($dbLookupUrl, {
        headers => {
            User => 'cassandane',
            Key => $unshared1->uid,
        },
    });
    $self->assert_str_equals('204', $res->{status});

    # lookup ownGroupUid
    $res = $adminJmap->ua->get($dbLookupUrl, {
        headers => {
            User => 'cassandane',
            Key => $owngroup1->uid,
        },
    });
    $self->assert_cmp_deeply(bag( 'ownGroup@local',
                                  'sharedcontact@local',
                                  'sharedcontact2@local' ),
                             decode_json($res->{content}));

    # lookup sharedGroupUid
    $res = $adminJmap->ua->get($dbLookupUrl, {
        headers => {
            User => 'cassandane',
            Key => $sharedgroup1->uid,
        },
    });

    $self->assert_cmp_deeply(bag( 'ownContact@local',
                                  'sharedcontact@local' ),
                             decode_json($res->{content}));

    # own addressbook is NOT shared with other2
    $res = $adminJmap->ua->get($dbLookupUrl, {
        headers => {
            User => 'other2',
            Key => $own1->uid,
        },
    });
    $self->assert_str_equals('204', $res->{status});

    # shared addressbook is NOT shared with other2
    $res = $adminJmap->ua->get($dbLookupUrl, {
        headers => {
            User => 'other2',
            Key => $shared1->uid,
        },
    });
    $self->assert_str_equals('204', $res->{status});
}
